Repository abiriadev/seia, pull requests merged in 2024-06, with the labels that each got.

#6 chore: fix typo
  README.md
  packages/seia/README.md
  packages/seia/src/process-polyfill.ts
Labels: bug, documentation

#12 build: setup GHA for chnagesets
  .github/workflows/release.yml
Labels: enhancement

#9 feat: create-seia-app
  .changeset/khaki-pillows-prove.md
  packages/create-seia-app/.eslintignore
  packages/create-seia-app/.prettierignore
  packages/create-seia-app/.swcrc
  packages/create-seia-app/.xo-config.json
  packages/create-seia-app/bin/create-seia-app.js
  packages/create-seia-app/package.json
  packages/create-seia-app/src/bin/create-seia-app.ts
  packages/create-seia-app/src/index.ts
  packages/create-seia-app/templates/javascript/.gitignore
  packages/create-seia-app/templates/javascript/README.md.liquid
  packages/create-seia-app/templates/javascript/package.json.liquid
  packages/create-seia-app/templates/javascript/src/App.jsx
  packages/create-seia-app/templates/javascript/src/Counter.jsx
  packages/create-seia-app/templates/javascript/src/Footer.jsx
  packages/create-seia-app/templates/javascript/src/vite-env.d.ts
  packages/create-seia-app/templates/typescript/.gitignore
  packages/create-seia-app/templates/typescript/README.md.liquid
  packages/create-seia-app/templates/typescript/package.json.liquid
  packages/create-seia-app/templates/typescript/src/App.tsx
  packages/create-seia-app/templates/typescript/src/Counter.tsx
  packages/create-seia-app/templates/typescript/src/Footer.tsx
  packages/create-seia-app/templates/typescript/src/vite-env.d.ts
  packages/create-seia-app/templates/typescript/tsconfig.json
  packages/create-seia-app/templates/typescript/tsconfig.node.json
  packages/create-seia-app/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#18 fix(create-seia-app/ts-template): correct `@types/react-dom` version to `^18.3.0`
  packages/create-seia-app/templates/typescript/package.json.liquid
Labels: bug

#23 fix(create-seia-app): replace `import.meta.dirname` with compatible alternative
  packages/create-seia-app/src/index.ts
Labels: enhancement

#26 fix: force serve command to render JSX in production mode
  .changeset/hot-tomatoes-divide.md
  packages/seia/src/commands/start.ts
Labels: bug

#29 docs: made a dedicated section for awesome sponsors!
  README.md
Labels: documentation

#30 readme.md에 create-seia-app 소개, 명령어 설명 추가했습니다.
  README.md
Labels: documentation

#32 chore: setup auto_assign bot
  .github/auto_assign.yml
Labels: size/XS

#34 Improve issue & pr templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc.yml
  .github/ISSUE_TEMPLATE/enhance.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: size/L

#35 chore: add a section for additional contexts to issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/doc.yml
  .github/ISSUE_TEMPLATE/enhance.yml
Labels: size/S

#37 setup vitest
  .github/workflows/ci.yml
  .gitignore
  package.json
  packages/seia/package.json
  pnpm-lock.yaml
  turbo.json
  vitest.workspace.json
Labels: size/XL

#38 move pr template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
Labels: size/S
